-- AlterTable
ALTER TABLE "User" ADD COLUMN     "documentsViewed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastSignIn" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "numberOfSignIns" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "timeSpent" INTEGER NOT NULL DEFAULT 0;
